[package]
name = "RedTokyoSupportBot"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false
rpath = false
incremental = false

[lints.clippy]
too_many_arguments = "allow"

[dependencies]
tokio = { version = "1.53.1", default-features = false, features = ["rt-multi-thread", "macros"] }
telers = { version = "1.0.0-beta.8", default-features = false, features = ["signal"] }

sea-orm = { version = "2.0.0", default-features = false, features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono"] }
moka = { version = "0.12.15", default-features = false, features = ["future"] }

serde = { version = "1.0.228", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.151", default-features = false, features = ["std"] }

reqwest = { version = "0.13.4", default-features = false, features = ["query", "json", "rustls"] }

chrono = { version = "0.4.45", default-features = false, features = ["std", "clock", "serde"] }
chrono-tz = { version = "0.10.4", default-features = false, features = ["filter-by-regex"] }
uuid = { version = "1.23.4", default-features = false, features = ["v4", "serde"] }

tracing = {version = "0.1.44", default-features = false}
tracing-subscriber = { version = "0.3.23", default-features = false, features = ["env-filter", "fmt", "ansi"] }

strum = { version = "0.28.0", default-features = false, features = ["derive"] }
smallvec = { version = "2.0.0-alpha.12", default-features = false }
dotenvy = { version = "0.15.7", default-features = false }
rand = { version = "0.10.2", default-features = false }
anyhow = { version = "1.0.104", default-features = false }
thiserror = { version = "2.0.19", default-features = false }
regex = { version = "1.13.1", default-features = false, features = ["unicode-perl"] }